apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: microservices
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservices-role
  namespace: microservices
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microservices-rolebinding
  namespace: microservices
subjects:
- kind: ServiceAccount
  name: microservices-sa
  namespace: microservices
roleRef:
  kind: Role
  name: microservices-role
  apiGroup: rbac.authorization.k8s.io