apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-files
  namespace: microservices
data:
  application.yml: |
    spring:
      profiles:
        active: native
      cloud:
        config:
          server:
            native:
              search-locations: file:/config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: microservices
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
      containers:
      - name: config-server
        image: bluewhale007/configserver:latest
        resources:
          limits:
            memory: "700Mi"
            cpu: "500m"
          requests:
            memory: "300Mi"
            cpu: "100m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "native"
        - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
          value: "/config"
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-password
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-vhost
        volumeMounts:
        - name: config-volume
          mountPath: /config
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: config-server-files
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  selector:
    app: config-server
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP