apiVersion: apps/v1
kind: Deployment
metadata:
  name: flog
  namespace: microservices
  labels:
    app: flog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flog
  template:
    metadata:
      labels:
        app: flog
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: flog
        image: mingrammer/flog:latest
        command: ["flog", "-f", "json", "-d", "200ms", "-l"]
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: flog
  namespace: microservices
spec:
  selector:
    app: flog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP