apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: microservices
  labels:
    app: gateway-service
spec:
  serviceAccountName: microservices-sa
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z mongo.microservices 27017; do echo waiting for mongo; sleep 2; done;"]
      - name: wait-for-rabbitmq
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z rabbitmq.microservices 5672; do echo waiting for rabbitmq; sleep 2; done;"]
      - name: wait-for-eureka-server
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z eureka-server.microservices 8761; do echo waiting for eureka-server; sleep 2; done;"]
      - name: wait-for-keycloak
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z keycloak.microservices 8080; do echo waiting for keycloak; sleep 2; done;"]
      - name: wait-for-config-server
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z config-server.microservices 8888; do echo waiting for config-server; sleep 2; done;"]
      containers:
      - name: gateway-service
        image: bluewhale007/gateway:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "300Mi"
            cpu: "100m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-password
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-vhost
        volumeMounts:
        - name: log-volume
          mountPath: /logs
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: log-volume
        hostPath:
          path: /mnt/data/logs
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservices
spec:
  selector:
    app: gateway-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP