apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z kafka.microservices 9092; do echo waiting for kafka; sleep 2; done;"]
      - name: wait-for-config-server
        image: busybox:1.36
        command: ["sh", "-c", "until nc -z config-server.microservices 8888; do echo waiting for config-server; sleep 2; done;"]
      containers:
      - name: notification-service
        image: bluewhale007/notification:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "300Mi"
            cpu: "100m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        volumeMounts:
        - name: log-volume
          mountPath: /logs
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: log-volume
        hostPath:
          path: /mnt/data/logs
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP