apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: microservices-sa
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
      containers:
      - name: order-service
        image: bluewhale007/order:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "300Mi"
            cpu: "100m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: db-url
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: db-password
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-password
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-vhost
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP