apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices
  labels:
    app: user-service
spec:
  serviceAccountName: microservices-sa
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      securityContext:
        runAsNonRoot: true
      containers:
      - name: user-service
        image: bluewhale007/user:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "300Mi"
            cpu: "100m"
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/ecom_user"
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-password
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: microservices-secrets
              key: rabbitmq-vhost
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP